apiVersion: apps/v1
kind: Deployment
metadata:
  name: dt-container-aks
spec:
  selector:
      matchLabels:
        app: dt-container-aks
  replicas: 3
  template:
      metadata:
        labels:
            app: dt-container-aks
      spec:
        containers:
        - name: ansys-hybrid-twin
          image: tbcontainer220629.azurecr.io/ansys/hybrid_twin:23.1
          ports:
            - containerPort: 9080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256"
              cpu: 11400G
---
apiVersion: v1
kind: Service
metadata:
  name: dt-container-aks-loadbalancer-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      name: port80
      port: 80
      protocol: TCP
  selector:
    app: dt-container-aks
